### ISSUE TITLE
Connection issues + integration not loading: can not connect to former api "api-v2launch.trakt.tv", integration needs to switch to new "api.trakt.tv

### ISSUE THREAD

**Issue by Tomasz-Matuszewski** [custom-components/sensor.trakt#72] opened 2024-02-04 13:30 UTC
Hi
I have been trying to run this add-on for several days but without success,  I keep seeing this synchronization error in the log,  ID , secrets and Redirect URI from the trakt.tv API is correct, any sugestion what I'm doing wrong ?  , HA is latest docker images 2024.3.0.dev20240202  , but also trying on stable and other dev version 

2024-02-04 14:18:00.104 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Trakt for trakt_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 442, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/__init__.py", line 63, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 278, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 445, in retrieve_data
    sources_data = await gather(*coroutine_sources_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 341, in fetch_upcomings
    data = await gather(
           ^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 273, in fetch_upcoming
    data = await gather(
           ^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 108, in fetch_calendar
    response = await self.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 77, in request
    response = await self.web_session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1101, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1004, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 637, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by henel321** [comment] 2024-02-05 09:23
I also see this on my installation. Looks like the custom component is using the old API, api-v2launch.trakt.tv , that was closed on Feb 1st...  Need to update to use api.trakt.tv

https://twitter.com/traktapi/status/1742976564567106019

2024-02-05 10:21:12.110 ERROR (MainThread) [custom_components.trakt] Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa420c32910>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by jarooij** [comment] 2024-02-05 16:34
Go to your custom_components folder and go to the trakt folder.
Open const.py with your notepad app (or better Notepad++)
Change the 2 faulty api-v2launch.trakt.tv in const.py in:

https://api.trakt.tv/oauth/token
and
https://api.trakt.tv/oauth/authorize

and it will work again

**Comment by bcutter** [comment] 2024-02-05 23:11
Same here. Restarted HA after roughly a month. When the integration tries to load it also complains it can not connect to the API `api-v2launch.trakt.tv`...

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.trakt
Source: helpers/update_coordinator.py:226
Integration: Trakt (documentation)
First occurred: 5. Februar 2024 um 23:44:05 (16 occurrences)
Last logged: 00:02:46

Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f319b14b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f31f08ee0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56d1a830>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f722582e0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2cb45990>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

As it's not just another hostname but likely a new API, just locally redirecting old `api-v2launch.trakt.tv` to new `api.trakt.tv` on DNS level will likely help nothing.

So: HELP! :-(

Who can fix this? Last update from 2022, now the integration is completely broken and more users are discovering this, once their HA restarts...

**Comment by LeandroIssa** [comment] 2024-02-06 01:50
> Same here. Restarted HA after roughly a month. When the integration tries to load it also complains it can not connect to the API `api-v2launch.trakt.tv`...
> 
> ```
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: custom_components.trakt
> Source: helpers/update_coordinator.py:226
> Integration: Trakt (documentation)
> First occurred: 5. Februar 2024 um 23:44:05 (16 occurrences)
> Last logged: 00:02:46
> 
> Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f319b14b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f31f08ee0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56d1a830>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f722582e0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-06/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2cb45990>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> ```
> 
> As it's not just another hostname but likely a new API, just locally redirecting old `api-v2launch.trakt.tv` to new `api.trakt.tv` on DNS level will likely help nothing.
> 
> So: HELP! :-(
> 
> **Who can fix this?** Are you able to fix it @iantrich? Last update from 2022, now the integration is completely broken and more users are discovering this, once their HA restarts...
> 
> Following what @henel321 posted: Wow, deprecated for more than 6 years and the final call from January 4th also got no attention... this integration/repo is not dead, is it?
> 
> No idea if it's "just" adapting this to the new API:
> 
> https://github.com/custom-components/sensor.trakt/blob/e6ce74f767d68338e37e4ccb1f2a52844c8679ba/custom_components/trakt/const.py#L4
> 
> https://github.com/custom-components/sensor.trakt/blob/e6ce74f767d68338e37e4ccb1f2a52844c8679ba/custom_components/trakt/const.py#L5
> 
> @Tomasz-Matuszewski Could you please rename this issue to something like "Connection issues + integration not loading: can not connect to former api "api-v2launch.trakt.tv", integration needs to switch to new "api.trakt.tv" instead"?

Same problem here!

Este erro originou-se de uma integração personalizada.

Logger: custom_components.trakt
Source: helpers/update_coordinator.py:313
Integration: Trakt (documentation)
First occurred: 12:22:29 (479 occurrences)
Last logged: 22:44:22

Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78c57d3b10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792547a4d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7925478e90>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f790e29ccd0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7924cd9cd0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by taw123** [comment] 2024-02-06 07:28
Let me up front say in NO WAY understand the internals of Home Assistant or even HA integrations....

HOWEVER as an Engineer for more years than I can now count before moving to the Dark Side (Mgt). lol  I was able to figure out SOME of what is going on here...

After deleting my config and trying to re-add back in this integration I was able to confirm that the issue here is the removal of the the old api-v2launch.trakt.tv hosts (per comments here and on [twitter](https://twitter.com/traktapi/status/1742976564567106019). Seems they deprecated the server but the API should still work so..... ever the hack...

I hacked up the Integration. Specifically editing **const.py** revising the authorize and token URL as follows 

```
OAUTH2 AUTHORIZE = "https://api.trakt.tv/oauth/authorize"
OAUTH2 TOKEN = "https://api.trakt.tv/oauth/token"
```

After revising, I am able to now get an Oauth token for Trakt in HA and add the integration.....   HOWEVER I am now getting the error everyone else has whenever the integration trys to update/refresh  

```
Logger: custom_components.trakt
Source: helpers/update_coordinator.py:313 
Integration: Trakt ([documentation](https://github.com/custom-components/sensor.trakt/blob/master/README.md)) 
First occurred: 10:45:19 PM (29 occurrences) 
Last logged: 11:14:24 PM

Error requesting trakt data: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /calendars/my/shows/2024-02-05/30 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8892b68d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

```

This SHOULD be simple to fix IF I could figure out where the call/code for the update lies. I looked through all the in the repo and can't seem to find where it's pulling the host name from. I was HOPING that was just building it from the cont file I updated but it seems like it's somewhere else SO  if anyone can figure out where it's coming from it should be is simple to get this back up.

As I said I have never written a line of Python in my life and while I can occasionally fight may way through YAML when needed I am at the end of what I can do here I suspect....  HOPEFULLY someone else can pick the ball up here and put it across the line.

Thanks!  (yes I know about the other trakt integration with by the way DOES work).....    and is bring maintained so.....   if this code is has been abandoned then we should push HACS to mark it as such and remove it from HACS as it's non-functional as implemented and folks should move to get this [ACTIVELY updated fork](https://github.com/dylandoamaral/trakt-integration) into HACS as a replacement.

Thoughts on decommissioning this and/or which file to hack up with the new server host?

**Comment by GaelBarone** [comment] 2024-02-22 09:02
@taw123 : as you can see in `manifest.json`, `sensor.trakt` is based over [PyTrakt](https://github.com/moogar0880/PyTrakt).
You can find reference to api-v2 [here](https://github.com/moogar0880/PyTrakt/blob/master/trakt/core.py#L28)
Sadly it seems PyTrakt is no more maintained too ... https://github.com/moogar0880/PyTrakt/issues/216, but there is a [fork](https://github.com/glensc/python-pytrakt).
Maybe it's possible to change `sensor.trakt` backend with some work ...

**Comment by bcutter** [comment] 2024-02-22 09:30
I vote for switching to the fork which seems to be very actively maintained.

Who is able to implement this? Will there be an approval by the owner of this repository?

**Comment by taw123** [comment] 2024-02-26 23:05
> Who is able to implement this? Will there be an approval by the owner of this repository?

Not sure how that works for HACS integrations.....

In THEORY when this bug is opened for a HA Integration the BOT automatically copies the integration over and asks them to look at the integration. My suggestion would be to find the ORIGINAL integration announcement on the Home Assistance forum and see if the author is the OP...  Then you can ping them direct. If they don't respond then think you are out of luck in general as someone will need to fork this repo and port it to the new API and prequalify it for HACS (or just let us know they have made the mods and wee can each replace our current configs with their PRIVATE repo.

**Comment by iantrich** [comment] 2024-02-27 21:17
We can get new maintainers added to this repo; email me at iantrich@gmail.com. I’m no longer able to actively maintain

**Comment by bcutter** [comment] 2024-02-27 22:40
OK everyone that's not perfect but in a way good news! So if someone can fix this issue by adjusting this integration to use the new API, the PR is able to be merged by someone who got in contact with https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-1967605941.

As there are other integrations using the "new" API (like https://github.com/dylandoamaral/trakt-integration), it should be possible to make the necessary adjustments - right?

So who has the skills here 😃

**Comment by taw123** [comment] 2024-02-29 17:35
Unfortunately as I said I don't know python ore enough about the internals of HA (and GitHub) to take this on. I can offer the simple hack I made above to get the integration to add which of course forks for Auth. What I DON'T know is where/how the code exists that ACTUALLY calls for data from Trakt.

Again all that I think needs two be done here is CHANGE the name of the server. API for auth is still the same so it should be a single change (assuming the server name is abstracted to a field/variable in the code like it is in the hack I made.

Sorry can't offer more I COULD ask a ton of questions (what is the process/component flow here for the integration, where are the files involved, how do you set up GitHub so my account is set up as an authorized contributor / or transfer control of integration source control, how to get it BACK to HA in a form they will accept (assuming- and it's a BIG assumption! that nothing else needs to be done to "modernize" the code)...   EVEN if I got the info for all that I would gladly look into making the change but things would be VERY fragile as again as I would just be searching the code for the original server address/API and substituting the revision by gleaming what I can from looking at the logic of the code. All programing languages have similarities in logic but again I don't know python, so not a good long term owner for the codebase.  

BUT a willing person to help (test, review code, provide insight, etc) or anything else someone needs. And at least you can see my offering/code tweek above ;)

So the search continues.....

**Comment by bcutter** [comment] 2024-02-29 18:00
> Again all that I think needs two be done here is CHANGE the name of the server. API for auth is still the same so it should be a single change (assuming the server name is abstracted to a field/variable in the code like it is in the hack I made.

Wait, really? Did you test this with your local productive installation of the integration? One could simply hack this locally and test if it works.

I always assumed (no matter why) the API itself changed meaning there's a need to also adjust the requests.
If you tested this and it works "just" with the new API url... with that confidence it could be easy to submit a PR nad hopefully have iantrich just approve that. Not sure what's needed to finally pack that in a new release or if he (according to https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-1967605941) only wants fixed new maintainers - but step by step.

**Comment by taw123** [comment] 2024-02-29 18:41
The change I made ONLY effects the Integration config (changing the server). This will allow the INITIAL oAuth to succeed and the integration to config & load...   This is of no PRACTICAL value as future calls via python library will fail as the API server address IS NOT pulled from where I changed it. It DOES however STRONGLY indicate that IF the same change of address is made (and assuming the code LIKEWISE abstracts the server address as I mentioned) then it should be a simple matter of making a likewise single change to THAT file....

These 2 hacks would fix things LOCALLY for someone (as the first did for me), but 2 issues IF one were to go with this quick and dirty hack approach...

1. These changes would get overwritten by future HA updates/docker images/etc.  
2. Possible consequences downstream consequences to other components/integrations/etc that were ALSO issuing the SHARED Python Trakd library you need to hack up to use the new API server address...   Might be ok/good as they would also keep working but not a good long term solution in general because this would be COMPLETELY UNSUPORTABLE...

Right solution as was stated by #[GaelBarone](https://github.com/GaelBarone) is to move this integration to a SUPPORTED fork of the library (which I found- [PyTrakt](https://github.com/glensc/python-pytrakt)). It was actually created bye someone for the same reason as we have. API changed and orignal author of the (GENERAL PURPOSE) python lib for Trakt has abandoned it, and he kindly stepped up to to fork and update adding over 15 changes....

From what I have SEEN the **pytrakt** library APIs are exactly the same (at this point) as the abandoned library so **in THEORY all one needs to do is change THIS integration to point at @glensc's current and maintained [forked version](https://github.com/glensc/python-pytrakt) rather than @moogar0880's  [abandoned version](https://github.com/moogar0880/PyTrakt/issues/199).**

**Comment by bcutter** [comment] 2024-03-17 00:38
So this integration is still DEAD... will it stay in that state?
If so, it will be removed from HACS.

**Comment by bcutter** [comment] 2024-03-26 10:25
Still no update... what a pity. I guess someone will request to remove this integration from HACS. Broken integrations should not exist there, leading to frustrating new users (like the old ones currently).

**Comment by glensc** [comment] 2024-03-26 22:26
why doesn't whoever who uses and needs this, send pr to change this line to `pytrakt==3.4.31`:
- https://github.com/custom-components/sensor.trakt/blob/e6ce74f767d68338e37e4ccb1f2a52844c8679ba/custom_components/trakt/manifest.json#L7

**Comment by bcutter** [comment] 2024-03-27 09:35
Seems like here's a mix of people
- who seem to know (or suspect) what needs to be done to fix this but don't create a PR
- who are willing to submit a OR but have no idea what needs to be changed at which places (that's me)
- who would as previous/current maintainers likely not merge PRs as they already mentioned they need new maintainers

That whole situation is a bit strange. As mentioned I could submit PRs but have no idea what needs to be done and J won't be able to test it etc.

This integration needs a new maintainer otherwise it will be dead :-(

**Comment by bcutter** [comment] 2024-05-06 16:20
And still dead.

**Comment by glensc** [comment] 2024-05-07 06:36
@bcutter you start by leading an example. i.e take these instructions and start a pr:
- https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-2021576003

alternatively, you could just find source code in your local install, and replace all occurrences of `https://api-v2launch.trakt.tv` with `https://api.trakt.tv`

**Comment by taw123** [comment] 2024-05-08 17:51
> why doesn't whoever who uses and needs this, send pr to change this line to `pytrakt==3.4.31`:
> 
THANK YOU @glensc 

This was the missing piece as I didn't/still don't adequately understand HA internals but trying too learn as I get time btwn my own ZFS issues but I digress.

Combine my hack at the top (also kindly included by @glensc ) to get proper credentials with the missing piece supplied by him to make the sensor code use the newer library and the sensor will again work properly!

@bcutter What he referenced DOES work and should be the basis for your PR. Again I just don't have the cycles and (as witnessed by my inability to figure out what needed to be changed to get the integration onto the newer library) clearly demonstrates I am not presently qualified to own the code so I really don't want to stick my finger in the pot. Perhaps one day that will change when I am better able to assist beyond what I have already done as just a hack.

I would suggest that you do the following 3 things.
1. File a PR as suggested so that you send up with a solution (eventually) that is supported, and benefits all. Hopefully picking up a bit of experience along the way, with gratitude from those who again can use the integration without resorting to workarounds.
2. Then if you would like a solution in the short term you can do as I did and hack upon the 2 files references, understanding that they WILL be replaced if ever the integration is updated (keep a backup of un-mod files and backup of your mods should you need to restore them after an update). There are undoubtably better ways to doo this like forking the code and using your fork in place of the mainline source tree but again at the moment that is beyond my knowledge base and the time I have to investigate further.
3. In opening the PR and adding the details of the 2 file fixes I would suggest providing a link to the PR here as it will serve as a good reference for anyone ELSE needing to get the integration up and running before someone picks up the PR.

Sorry I can"t offer more assistance but it looks like you should be in good shape to go now knowing that the workaround DOES work.

Regards,
T

**Comment by bcutter** [comment] 2024-05-09 18:15
> https://api.trakt.tv



> @bcutter you can start by leading an example. i.e take these instructions and start a pr:
> 
>     * [Connection issues + integration not loading: can not connect to former api "api-v2launch.trakt.tv", integration needs to switch to new "api.trakt.tv #72 (comment)](https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-2021576003)
> 
> 
> alternatively, you could just find source code in your local install, and replace all occurrences of `https://api-v2launch.trakt.tv` with `https://api.trakt.tv`

Indeed it is working, confirmed after patching it locally. Only necessary changes are here exactly as described:

https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-2021576003

![grafik](https://github.com/custom-components/sensor.trakt/assets/13799156/19734ba6-25e1-4f45-8473-97c2803a8d6d)

![grafik](https://github.com/custom-components/sensor.trakt/assets/13799156/bfc75ef8-b2e5-4ede-be55-7dc9fae4d795)

![grafik](https://github.com/custom-components/sensor.trakt/assets/13799156/75cff998-ff4a-4c6c-95de-6d0b91e2f6db)

---

I now wanted to create the necessary PRs **but** the repository does not allow this currently:
![grafik](https://github.com/custom-components/sensor.trakt/assets/13799156/2ab3e485-3817-4925-a937-e70f6bdce5b4)

@iantrich @engrbm87 can you please
1. assist on how to create a PR
2. make a statement if you would merge them

I won't step up as a maintainer but I'm willing to support fixing this for others. This way maybe we can revoke the HACS removal flags.

---

**Summary:**
1) It can be fixed and the integration continues to work, but one has to patch it locally (e. g. using the SAMBA share: `\custom_components\trakt`
2) The integration will be removed from HACS (unless we at least fix THIS issue).
3) Creation of PRs not possible without support by @iantrich / @engrbm87.
4) Of course anyone could fork this repo, do the work and apply to register it as a new integration for HACS again.

**Comment by glensc** [comment] 2024-05-12 07:50
> Creation of PRs not possible without support by @iantrich / @engrbm87.

not true. you need to:
1. fork the project
2. make changes on new branch in your repo
3. push the changes got github
4. create pull request to this repository

if you fix the "not on the branch" from the UI (pick "master" as branch), then the rest of it you can basically do from web

**Comment by bcutter** [comment] 2024-05-12 09:16
@glensc 

Seeing
a) how skilled you are with how GitHub works and
b) that you came up with the original necessary changes

why don't you simply create those PRs.

**Comment by glensc** [comment] 2024-05-12 11:22
@bcutter I'm not using this project. no idea even what this even is. i got pulled in because someone mentioned active pytrakt fork.

**Comment by bcutter** [comment] 2024-05-12 23:02
> if you fix the "not on the branch" from the UI (pick "master" as branch), then the rest of it you can basically do from web

That did the trick. **Awaiting PRs to be merged.**
No idea what happens after that, cause a release needs to be build too I guess. I'm out for that.

**Closed** 2024-06-11 17:11 UTC
